Alan/feat/creat relative posts block
YayCommerce/Brandy-Blocks pull request #1
Opened 2024-03-27 09:16 UTC by pnTrungPham

2024-03-27 09:18 UTC, pnTrungPham commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create relative posts block](https://trello.com/c/5se3FuOH/173-create-relative-posts-block)

2024-03-31 04:54 UTC, thithiennta requested changes
@pnTrungPham bạn này check nhé

2024-03-31 04:54 UTC, thithiennta commented on inc/Packages/Blocks/RelativePosts.php
> +	public const RENDER_LIST_ACTION = 'brandy_blocks_relative_posts_render_list';
cái này chưa biết để làm gì hớt nè @pnTrungPham

2024-03-31 04:54 UTC, thithiennta commented on inc/Shortcodes/ShortcodesLoader.php
> +	public function brandy_relative_blogs( $atts ) {
Function name => có namespace rồi, k cần để prefix

2024-03-31 04:54 UTC, thithiennta commented on inc/Utils/Helpers.php
> +		$query_args = array(
này search post thôi á @pnTrungPham 
thêm post_type vào nữa

2024-03-31 04:57 UTC, thithiennta commented on inc/Packages/Blocks/RelativePosts.php
> +		if ( ! function_exists( 'WC' ) ) {
Không cần check WC chỗ này

2024-04-05 04:30 UTC, merged